version: '3'

services:

  netcoreapp:
    image: 'netcoreapp:1.0'
    container_name: netcoreapp
    depends_on:
      - postgres
    build: 
      context: ./app/api
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION_STRING="host=postgres;port=5432;database=psqldatabase;username=psqladmin;password=psqlpasswd"
    ports:
      - '5001:80'

  # Postgres database container 
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_USER=psqladmin
      - POSTGRES_PASSWORD=psqlpasswd
      - POSTGRES_DB=psqldatabase
    # To store database data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/db/pgconf:/etc/postgresql
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: psqlpasswd
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
     
volumes:
  pgadmin-data:
  pgdata: