version: '3'

services:
  frontend:
    image: 'frontend:1.0'
    container_name: frontend
    # depends_on:
      # - netcoreapp
    build: 
      context: ./app/ui
      dockerfile: Dockerfile
    # To make use of hot-reloads
    volumes:
      - ./app/ui/frontend:/app
    ports:
      - '3000:3000'